### ISSUE TITLE
deletepdf_image.py  你好，想请教下，删除pdf里的图片，你的代码报错，怎么解决？微信 nlanguage

### ISSUE THREAD

**Issue by nissansz** [pycgo/common-scripts#1]
bbox = page.get_image_rects(image[0][1])[image[0][1]]  # get bbox
IndexError: list index out of range

**Comment by pycgo** [comment]
image = page.get_images()  你要自己打印自己的是什么编号  不是直接照抄我的编号

**Comment by nissansz** [comment]
我是打印自己的编号，放进去也是报错，主要是图片在另一种图下方

**Comment by pycgo** [comment]
这个你自己研究一下呗 我这个很久之前搞的 没映像了

**Comment by nissansz** [comment]
想了解怎么删除全部元素，然后重建，去掉不要的，保留需要的

**Comment by nissansz** [comment]
作者更新了版本，现在可以用了。
